import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'
import { Providers } from "../redux/provider";
import "../style.css"
import BootstrapClient from "@/components/BootstrapClient";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Providers>{children}</Providers>
        <BootstrapClient/>
      </body>
    </html>
  );
}
