export const LOCATION = "LOCATION";
export const APARTMENT = "APARTMENT";
export const GET_APARTMENTS_FETCH = "GET_APARTMENTS_FETCH";
export const GET_APARTMENTS_SUCCESS = "GET_APARTMENTS_SUCCESS";
export const GET_APARTMENTS_FAILURE = "GET_APARTMENTS_FAILURE";
